language: java
dist: trusty
jdk:
  - oraclejdk8
sudo: true
before_install:
  - chmod +x mvnw
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V